version: "3"

services:
  website:
    image: ghcr.io/the-renee-project/project-site
    deploy:
      placement:
        constraints:
          - node.hostname == panik3
    ports:      
      - target: 80
        published: 9090
        mode: host